export default {
    GET_ROLES: 'GET_ROLES',
    GET_ROLES_FULFILLED: 'GET_ROLES_FULFILLED',
    GET_ROLE: 'GET_ROLE',
    GET_ROLE_FULFILLED: 'GET_ROLE_FULFILLED',
    DELETE_ROLE: 'DELETE_ROLE',
    CREATE_ROLE: 'CREATE_ROLE',
    UPDATE_ROLE: 'UPDATE_ROLE'
}