export default {
    GET_PROFILES: 'GET_PROFILES',
    GET_PROFILES_FULFILLED: 'GET_PROFILES_FULFILLED',
    GET_PROFILE: 'GET_PROFILE',
    GET_PROFILE_FULFILLED: 'GET_PROFILE_FULFILLED',
    CREATE_PROFILE: 'CREATE_PROFILE',
    CREATE_PROFILE_FULFILLED: 'CREATE_PROFILE_FULFILLED',
    UPDATE_PROFILE: 'UPDATE_PROFILE',
    UPDATE_PROFILE_FULFILLED: 'UPDATE_PROFILE_FULFILLED',
    DELETE_PROFILE: 'DELETE_PROFILE',
    DELETE_PROFILE_FULFILLED: 'DELETE_PROFILE_FULFILLED',
}