export default {
    GET_PERMISSIONS: "GET_PERMISSIONS",
    GET_PERMISSIONS_FULFILLED: 'GET_PERMISSIONS_FULFILLED',
    GET_PERMISSION: "GET_PERMISSION",
    GET_PERMISSION_FULFILLED: "GET_PERMISSION_FULFILLED",
    CREATE_PERMISSION: "CREATE_PERMISSION",
    UPDATE_PERMISSION: "UPDATE_PERMISSION",
    DELETE_PERMISSION: "DELETE_PERMISSION",
}