export default {
    GET_PERMISSIONS: "GET_PERMISSIONS",
    GET_PERMISSIONS_FULFILLED: "GET_PERMISSIONS_FULFILLED",
    GET_PERMISSION: "GET_PERMISSION",
    GET_PERMISSION_FULFILLED: "GET_PERMISSION_FULFILLED",
    CREATE_PERMISSION: "CREATE_PERMISSION",
    CREATE_PERMISSION_FULFILLED: "CREATE_PERMISSION_FULFILLED",
    UPDATE_PERMISSION: "UPDATE_PERMISSION",
    UPDATE_PERMISSION_FULFILLED: "UPDATE_PERMISSION_FULFILLED",
    DELETE_PERMISSION: "DELETE_PERMISSION",
    DELETE_PERMISSION_FULFILLED: "DELETE_PERMISSION_FULFILLED",
    SORT_PERMISSION: "SORT_PERMISSION",
    PERMISSION_ID: "PERMISION_ID",
    IS_DELETE_PERMISSION: "IS_DELETE_PERMISSION",
    ACTIVE_PAGE: "ACTIVE_PAGE",
    PAGE_LIMIT: "PAGE_LIMIT",
    GET_SERVICES: "GET_SERVICES",
    GET_SERVICES_FULFILLED: "GET_SERVICES_FULFILLED"
}