export default {
    LOGIN: 'LOGIN',
    LOGIN_FULFILLED: 'LOGIN_FULFILLED',
    LOGOUT: 'LOGOUT',
    GET_PROFILE: 'GET_PROFILE',
    GET_PROFILE_FULFILLED: 'GET_PROFILE_FULFILLED',
    GET_USERS: 'GET_USERS',
    GET_USERS_FULFILLED: 'GET_USERS_FULFILLED',
    GET_USERS_REJECTED: 'GET_USERS_REJECTED'
}