export default {
    GET_SHOP_PRODUCT: 'GET_SHOP_PRODUCT',
    GET_SHOP_PRODUCT_FULFILLED: 'GET_SHOP_PRODUCT_FULFILLED',
    GET_SHOP_PRODUCT_REJECTED: 'GET_SHOP_PRODUCT_REJECTED',

    GET_PAGINATED_SHOP_PRODUCT: 'GET_PAGINATED_SHOP_PRODUCT',
    GET_PAGINATED_SHOP_PRODUCT_FULFILLED: 'GET_PAGINATED_SHOP_PRODUCT_FULFILLED',
    GET_PAGINATED_SHOP_PRODUCT_REJECTED: 'GET_PAGINATED_SHOP_PRODUCT_REJECTED',

    GET_SORTED_SHOP_PRODUCT: 'GET_SORTED_SHOP_PRODUCT',
    GET_SORTED_SHOP_PRODUCT_FULFILLED: 'GET_SORTED_SHOP_PRODUCT_FULFILLED',
    GET_SORTED_SHOP_PRODUCT_REJECTED: 'GET_SORTED_SHOP_PRODUCT_REJECTED',
}