export default {
    SHOP_LOGIN: 'SHOP_LOGIN',
    SHOP_LOGIN_FULFILLED: 'SHOP_LOGIN_FULFILLED',
    SHOP_LOGOUT: 'SHOP_LOGOUT',
    GET_SHOP_PROFILE: 'GET_SHOP_PROFILE',
    GET_SHOP_PROFILE_FULFILLED: 'GET_SHOP_PROFILE_FULFILLED',
    GET_SHOP: 'GET_SHOP',
    GET_SHOP_FULFILLED: 'GET_SHOP_FULFILLED',
    GET_SHOP_REJECTED: 'GET_SHOP_REJECTED'
}