export default {
    GET_PRODUCTS: 'GET_PRODUCTS',
    GET_PRODUCTS_FULFILLED: 'GET_PRODUCTS_FULFILLED',
    GET_PRODUCTS_REJECTED: 'GET_PRODUCTS_REJECTED',

    GET_PRODUCT: 'GET_PRODUCT',
    GET_PRODUCT_FULFILLED: 'GET_PRODUCT_FULFILLED',
    GET_PRODUCT_REJECTED: 'GET_PRODUCT_REJECTED',

    ADD_PRODUCT: 'ADD_PRODUCT',
    DELETE_PRODUCT: 'DELETE_PRODUCT',
    UPDATE_PRODUCT: 'UPDATE_PRODUCT'
}